絵本リストの返事を可愛くする！
ikejirirb/ruboty-ehon pull request #20
Opened 2017-12-27 14:20 UTC by risacan

2017-12-28 07:09 UTC, katorie requested changes

2017-12-28 07:09 UTC, katorie commented on lib/ruboty/handlers/ehon.rb
> +            "#{e[:title]}は#{e[:count]}回読みました。最後に読んだのは#{(Date.today - e[:created_at]).numerator}日前です。"
`updated_at` が最後に読んだ日になるのでは！

2017-12-28 07:11 UTC, risacan commented on lib/ruboty/handlers/ehon.rb
> +            "#{e[:title]}は#{e[:count]}回読みました。最後に読んだのは#{(Date.today - e[:created_at]).numerator}日前です。"
その通りです！😵🙏

2018-03-15 12:33 UTC, katorie approved these changes

2018-03-23 01:21 UTC, risacan commented
放置しちゃってた 💦 夜見ます！ 👀

2019-02-19 02:02 UTC, merged